<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-CL7U3OFA" ignored="0" name="Different testng features" tests="16" failures="1" timestamp="04 Apr 2020 22:33:02 GMT" time="0.071" errors="0">
  <testcase name="sum" time="0.004" classname="testng.Invocationcount"/>
  <testcase name="sum" time="0.001" classname="testng.Invocationcount"/>
  <testcase name="sum" time="0.001" classname="testng.Invocationcount"/>
  <testcase name="sum" time="0.001" classname="testng.Invocationcount"/>
  <testcase name="sum" time="0.001" classname="testng.Invocationcount"/>
  <testcase name="sum" time="0.002" classname="testng.Invocationcount"/>
  <testcase name="sum" time="0.001" classname="testng.Invocationcount"/>
  <testcase name="sum" time="0.001" classname="testng.Invocationcount"/>
  <testcase name="sum" time="0.001" classname="testng.Invocationcount"/>
  <testcase name="sum" time="0.001" classname="testng.Invocationcount"/>
  <testcase name="googletitletest" time="0.001" classname="testng.TestNG"/>
  <testcase name="search" time="0.0" classname="testng.TestNG"/>
  <testcase name="loginTest" time="0.001" classname="testng.Testngfeatures"/>
  <testcase name="searchTest" time="0.001" classname="testng.Testngfeatures"/>
  <testcase name="infiniteloop" time="0.009" classname="testng.ExceptionTimeout">
    <failure type="org.testng.TestException" message="
Expected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method testng.ExceptionTimeout.infiniteloop() didn&amp;apos;t finish within the time-out 2">
      <![CDATA[org.testng.TestException: 
at java.lang.Integer.toString(Unknown Source)
at java.lang.String.valueOf(Unknown Source)
at java.io.PrintStream.print(Unknown Source)
at java.io.PrintStream.println(Unknown Source)
at testng.ExceptionTimeout.infiniteloop(ExceptionTimeout.java:15)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- infiniteloop -->
  <testcase name="testcase1" time="0.001" classname="testng.ExceptionTimeout"/>
</testsuite> <!-- Different testng features -->
